// Code generated by structmorph; DO NOT EDIT.

package pointers

func ConvertToOrganizationDTO(src Organization) OrganizationDTO {

	var __synthetic__Title *string
	if src.Title != *new(string) {
		__synthetic__Title = &src.Title
	}

	var __synthetic__Description string
	if src.Description != nil {
		__synthetic__Description = *src.Description
	}

	return OrganizationDTO{
		Title:       __synthetic__Title,
		Description: __synthetic__Description,
		Priority:    src.Priority,
	}
}

func ConvertToOrganization(src OrganizationDTO) Organization {

	var __synthetic__Title string
	if src.Title != nil {
		__synthetic__Title = *src.Title
	}

	var __synthetic__Description *string
	if src.Description != *new(string) {
		__synthetic__Description = &src.Description
	}

	return Organization{
		Title:       __synthetic__Title,
		Description: __synthetic__Description,
		Priority:    src.Priority,
	}
}
