// Code generated by structmorph; DO NOT EDIT.

package first

import "structmorph/test/differentpkg/second"

func ConvertToPersonDTO(src second.Person) PersonDTO {

	return PersonDTO{
		Name: src.Name,
		Age:  src.Age,
	}
}

func ConvertToPerson(src PersonDTO) second.Person {

	return second.Person{
		Name: src.Name,
		Age:  src.Age,
	}
}
