// Code generated by structmorph; DO NOT EDIT.

package main

func ConvertToPersonDTO(src Person) PersonDTO {
	return PersonDTO{
		Name: src.Name,
		Sex:  src.Sex,
	}
}

func ConvertToPerson(src PersonDTO) Person {
	return Person{
		Name: src.Name,
		Sex:  src.Sex,
	}
}
